name: translation_engine_openai
description: OpenAI translation engine
version: 0.1.3
homepage: https://github.com/biyidev/uni_translate

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_openai: ^2.0.1
  uni_translate_client: ^0.1.3
