name: translation_engine_iciba
description: Iciba translation engine
version: 0.1.6
homepage: https://github.com/biyidev/uni_translate

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.1.2
  uni_translate_client: ^0.1.3

dev_dependencies:
  mostly_reasonable_lints: ^0.1.2
  test: ^1.0.0
